# Generated by Django 6.0.7 on 2026-07-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('min_predicted_score', models.FloatField()),
                ('required_subjects', models.TextField(help_text='Comma-separated key subjects')),
                ('required_soft_skills', models.TextField(help_text='Comma-separated key soft skills')),
            ],
        ),
        migrations.CreateModel(
            name='CareerAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_area', models.CharField(max_length=100)),
                ('communication_skill', models.IntegerField()),
                ('teamwork_skill', models.IntegerField()),
                ('problem_solving_skill', models.IntegerField()),
                ('leadership_skill', models.IntegerField()),
                ('adaptability_skill', models.IntegerField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_assessments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField()),
                ('gap_notes', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='careers.careerassessment')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careers.careerprofile')),
            ],
        ),
    ]
