# Generated by Django 6.0.7 on 2026-08-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerassessment',
            name='Work_in_Pressure',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
