# Generated by Django 6.0.7 on 2026-08-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_careerassessment_work_in_pressure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerassessment',
            name='Work_in_Pressure',
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='creativity_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='critical_thinking_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='time_management_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='adaptability_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='communication_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='interest_area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='leadership_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='problem_solving_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='careerassessment',
            name='teamwork_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
