# Generated by Django 6.0.7 on 2026-08-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_remove_careerassessment_work_in_pressure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careerassessment',
            name='interest_area',
            field=models.CharField(blank=True, choices=[('software_engineering', 'Software Engineering'), ('data_analytics', 'Data Analytics'), ('ui_ux_design', 'UI/UX Design'), ('network_administration', 'Network Administration'), ('business_analysis', 'Business Analysis'), ('cybersecurity', 'Cybersecurity'), ('cloud_computing', 'Cloud Computing'), ('mobile_development', 'Mobile App Development'), ('artificial_intelligence', 'Artificial Intelligence / Machine Learning'), ('game_development', 'Game Development'), ('project_management', 'IT Project Management'), ('quality_assurance', 'Quality Assurance / Testing')], max_length=100),
        ),
    ]
