# Generated by Django 6.0.7 on 2026-08-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_seed_career_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerassessment',
            name='database_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='networking_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='programming_languages',
            field=models.CharField(blank=True, help_text='Comma-separated languages known', max_length=255),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='programming_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerassessment',
            name='web_dev_skill',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='min_study_time',
            field=models.IntegerField(blank=True, help_text='1-4 scale, matching SemesterStudyTime', null=True),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='required_programming_languages',
            field=models.TextField(blank=True, help_text='Comma-separated languages'),
        ),
        migrations.AddField(
            model_name='careerprofile',
            name='required_technical_skills',
            field=models.TextField(blank=True, help_text='Comma-separated technical skill fields'),
        ),
    ]