# Generated by Django 6.0.7 on 2026-09-28 05:31

import django.db.models.deletion
import teacher_access.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0003_course_student_course'),
        ('teacher_access', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherlink',
            name='student',
        ),
        migrations.RemoveField(
            model_name='teacherlink',
            name='teacher',
        ),
        migrations.CreateModel(
            name='TeacherAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.CharField(default=teacher_access.models.generate_token, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_grants', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_grants', to='accounts.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='TeacherLink',
        ),
    ]
